### ISSUE TITLE
How to move index page to site/blog?

### ISSUE THREAD

**Issue by TheStigger** [poole/poole#101]
I want to make static index page and move current index page to blog page.

I've created copy of index.html (blog.html). But template engine can't find any posts on site/blog. There is just empty page with two buttons (newer and older). [Link](http://thestigger.github.io/blog/).

**Comment by rahul-rkt** [comment]
Did you try changing the front-matter of your blog.md?

**Comment by TheStigger** [comment]
@rahul-rkt yes, but still there is no pages. Looks like template engine can't find paginator object.

**Comment by resir014** [comment]
The paginator plugin only works on `index.html` files.

To get around it you might want to move `blog.html` inside a `/blog`
directory and rename it back to `index.html`. That way the page will still
load up the paginated list of posts, but will also maintain its directory
structure.

**Comment by TheStigger** [comment]
@resir014 where do I need to create blog folder? In _site there is generated html documents. Please, can you explain how to do what you said.

**Comment by resir014** [comment]
@TheStigger Just create the folder on your site's root directory. 

Here's an example: https://github.com/resir014/resir014.github.io/blob/master/blog/index.html

**Comment by TheStigger** [comment]
@resir014 I've made everything like you but nothing changes.
This is my repository: https://github.com/TheStigger/TheStigger.github.io

**Comment by resir014** [comment]
@TheStigger ah, the same code still exists in your root `index.html`. You
need to replace them with something else to make it work.

**Comment by TheStigger** [comment]
@resir014 problem was with _config.yml :) I had to add some settings for paginator.
`paginate_path:       "blog/page/:num/"`

**Comment by resir014** [comment]
@TheStigger ah right. I forgot about that, sorry!

**Comment by TheStigger** [comment]
@resir014 thanks to your blog. I've found this solutions from its source code :) Also I think I've found other interesting features in your code which will be useful for me.
