### ISSUE TITLE
A Navigation Bar

### ISSUE THREAD

**Issue by Porasjeet** [poole/poole#110]
How about making a bar at the top having links to all the pages of the website.

**Comment by eka-putra** [comment]
look like
![screenshot - 261015 - 21 38 28](https://cloud.githubusercontent.com/assets/8128165/10731867/f7c4271c-7c29-11e5-92f7-19e988656b4e.png)

**Comment by mdo** [comment]
Not for the base theme. If you need nav, check out Lanyon or Hyde :).
