### ISSUE TITLE
2a. Quickstart  in README requires context or more info.

### ISSUE THREAD

**Issue by pjakobsen** [poole/poole#112]
The README implies that getting started is easy, but there must be a missing step or some context that is required:
## 2a. Quick start

To help anyone with any level of familiarity with Jekyll quickly get started, Poole includes everything you need for a basic Jekyll site. To that end, just download Poole and start up Jekyll.

Following this instruction results in:

```
Configuration file: /Users/itsme/source/jekyll/poole-master/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /Users/itsme/source/jekyll/poole-master
       Destination: /Users/itsme/source/jekyll/poole-master/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Liquid syntax error: Unknown tag 'gist' in /Users/itsme/source/jekyll/poole-master/_posts/2014-01-01-example-content.md/#excerpt
  Liquid Exception: Liquid syntax error: Unknown tag 'gist' in _layouts/post.html
jekyll 3.0.0 | Error:  Liquid syntax error: Unknown tag 'gist'
```

**Comment by keithwi** [comment]
+1

**Comment by jun1st** [comment]
+1

**Comment by jun1st** [comment]
add `jekyll-gist` to gems in `_config.yml` file

```
gems:
  - jekyll-sitemap
  - jekyll-gist
```

**Comment by smutek** [comment]
` jekyll-sitemap` throws the following error for me. 

`Configuration file: /Users/.../kernel_require.rb:126:in `require': cannot load such file -- jekyll-sitemap (LoadError)`

Steps that get me up and running are - 

- Remove `relative_permalinks: true` from config.yaml
- Add: 
```
gems:
- jekyll-gist
- jekyll-paginate
```
After this `jekyll serve` will run for me with no issues.

**Comment by demidovakatya** [comment]
:+1:

**Comment by nicolasmccurdy** [comment]
These are in the config now, so existing users should merge in the new changes.
