### ISSUE TITLE
Are changes in poole manually merged into lanyon and hyde?

### ISSUE THREAD

**Issue by kihonkai** [poole/poole#114]
I'm quite new to Jekyll so sorry if I've missed something.  I quite like the look and feel of these themes but after doing some testing and looking at the repositories I've noticed they don't seem that up to date or in sync.  Here's an example of a difference in the index page:

**master branches:**
poole = `<a href="{{ site.baseurl }}{{ post.url }}">`
lanyon = `<a href="{{ site.baseurl }}/{{ post.url }}">`
hyde = `<a href="{{ post.url }}">`

**master branches:**
poole = `<a href="{{ site.baseurl }}{{ post.url }}">`
lanyon = `<a href="{{ post.url }}">`
hyde = `<a href="{{ post.url }}">`

Then there's pull requests in both themes related to this:
lanyon = https://github.com/poole/lanyon/pull/105
hyde = https://github.com/poole/hyde/pull/101

I can't see any links between the three repositories so I was wondering how they could be kept up to date?  

For now I've already forked lanyon so I can test and share some ideas.  For actual use I guess all I can do is update a fork as best as I can and hope it fits if in the future the original repositories are updated.

I guess posts created in any Jekyll site can always be copied into a totally new Jekyll directory if my changes diverge too much.  I'm likely overthinking this and should just get on with it and worry about merging if I ever need to :grinning:

**Comment by mdo** [comment]
Yes, manually merged.
