### ISSUE TITLE
Add a notice to prevent accidental PRs from forks

### ISSUE THREAD

**Issue by nickmccurdy** [poole/poole#137]
I've noticed a lot of people submitting their forks of Poole (and the other themes) as pull requests by accident, without any descriptions. It seems like a lot of Poole users may be confused about how to use forks and/or pull requests with Jekyll themes.

While I understand that this isn't anyone's intention, these pull requests create a lot of noise when trying to track the development of Poole themes. Most of my GitHub notifications about watching these themes are for this type of pull request.

Fortunately, GitHub has a bunch of neat new tools that could help with this issue, such as a contribution notice on new PRs/issues (this could remind people to think twice about opening PRs that aren't meant as contributions) and templates for new PRs/issues (there could be some text remind users to only use PRs for contributions). Can we try using one (or both) of these features to reduce the number of accidental PRs in these projects?

**Comment by resir014** [comment]
@nicolasmccurdy Probably a simple "download" button for each theme at the [homepage](http://getpoole.com/) might deter people from just forking off of the base theme and accidentally PR them. There might be a better idea, but that's all I could think of for now.

I feel you though. I've been trying to follow this theme's development closely, but these false PRs just clog up my inbox most of the time it's no longer funny.
