### ISSUE TITLE
Blog commenting system built with AWS Lambda Question

### ISSUE THREAD

**Issue by lbrent2k** [poole/poole#140]
I think it would be great to use this serverless comment functionality.
https://github.com/jimpick/lambda-comments.git

I am not clear where I would "affix" this in my Hyde site so that comment box properly displays under posts.  The code snip is what the author suggests, but where would I put this?

<div id="lambda-comments"></div>
<script src="*** url from above ***"></script>

**Comment by mdo** [comment]
Not something I'm going to tackle, thanks though!
