### ISSUE TITLE
RSS Feed points to local host

### ISSUE THREAD

**Issue by JasonNewton1** [poole/poole#151]
Hi there,

I run Jekyll on my Mac using the 'bundle exec jekyll serve' which builds the site fine. However, for some reason, the atom.xml file seems to build an XML feed that points to my local host address.

Can anyone help me?

I'm running Jekyll 3.4.3

Kind Regards

**Comment by JasonNewton1** [comment]
Here is the atom.xml file in my Poole folder.

`---
layout: null
---

<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

 <title>{{ site.title }}</title>
 <link href="{{ site.url }}{{ site.baseurl }}/atom.xml" rel="self"/>
 <link href="{{ site.url }}{{ site.baseurl }}/"/>
 <updated>{{ site.time | date_to_xmlschema }}</updated>
 <id>{{ site.url }}</id>
 <author>
   <name>{{ site.author.name }}</name>
   <email>{{ site.author.email }}</email>
 </author>

 {% for post in site.posts %}
 <entry>
   <title>{{ post.title | xml_escape }}</title>
   <link href="{{ site.url }}{{ site.baseurl }}{{ post.url }}"/>
   <updated>{{ post.date | date_to_xmlschema }}</updated>
   <id>{{ site.url }}{{ post.id }}</id>
   <content type="html">{{ post.content | xml_escape }}</content>
 </entry>
 {% endfor %}

</feed>`

**Comment by nickmccurdy** [comment]
Make sure you point `url` in `_config.yml` at your production address, otherwise Jekyll will default to the local server.

**Comment by JasonNewton1** [comment]
Thanks, Nick. It's fine now.

Kind Regards
