### ISSUE TITLE
Navigation Bar Links are not in Alphabetical Order

### ISSUE THREAD

**Issue by bikegirl** [poole/poole#168]
Hi There!  I am building my first website with your project, I love it so much!
I was expecting that every time I created an file.md it would automatically be put in alphabetical order on the navigation bar.  The order on the nav bar is the most recent file.

Is there anyway to fix that?  Please let me know.
Here is my project https://bikegirl.github.io/

**Comment by mdo** [comment]
This only applies to Lanyon, so closing out here.
