### ISSUE TITLE
What's the difference between url and baseurl in _config.yml?

### ISSUE THREAD

**Issue by ZhaofengWu** [poole/poole#178]
And should I set both of them to `https://USERNAME.github.io/`?

**Comment by mdo** [comment]
You typically don't need `baseurl` if you're setting `url` to a custom domain (e.g., `example.com`). With a GitHub user repo, I think you might want to do `username.github.io` for `url` and `/repo-name` for the `baseurl`. I'd consult the Jekyll docs to be sure though.
