### ISSUE TITLE
Use SCSS with Jekyll 2

### ISSUE THREAD

**Issue by nicolasmccurdy** [poole/poole#51]
GitHub Pages now uses Jekyll 2.x, which supports SCSS, SASS, and CoffeeScript assets. I think it would be great if the styles could be switched to SCSS. It makes it easier to make code more modular, and configuration would be easier through variables and mixins.

Additionally, it is fairly easy to concatenate files with SCSS by simplifying including an SCSS file that only imports other files. Lowering the number of requests made is often very helpful for improving performance.

__Note:__ I would also like to see this with the Hyde and Layon themes. I personally only use Hyde right now, though I'm hoping this was the right repo to mention the issue in, since it's related to the Poole project in general.

**Comment by mdo** [comment]
Done with #55.
