### ISSUE TITLE
`Related Article` links are wrong?

### ISSUE THREAD

**Issue by babygau** [poole/poole#61]
Hi,

I have `poole` demo blog up and running but when I click on any demo `related article` links, it showed wrong path. I thought the issue is fixed at [#41](https://github.com/poole/poole/issues/41). But it seems not to work for me.

For example:
```
# Example content 01 Jan 2014
http://0.0.7.222/01/01/example-content/
```

**Comment by jimmitchell** [comment]
fix is to remove `{{ site.baseurl }}` param in _layout/posts.html template at line 17. `{{ post.url }}` param already includes baseurl.

**Comment by tcfraser** [comment]
@jimmitchell Your mentioned fix works. The pull request works as well but only on a live version of a site. Running locally, the related post's link to the live site. Therefore, {{site.url}} shouldn't be included.

**Comment by mdo** [comment]
Will be resolved with v2. Until then, you'll need to tweak the `baseurl`.
