### ISSUE TITLE
How to remove "Download" and "Github project" menu?

### ISSUE THREAD

**Issue by ghost** [poole/poole#76]
Sorry, i'm newbie...

**Comment by nicolasmccurdy** [comment]
This theme does not have navigation links. Are you asking about [Hyde](http://hyde.getpoole.com/) or [Lanyon](http://lanyon.getpoole.com/)?

**Comment by yusyulianto** [comment]
yes, hyde.

**Comment by nicolasmccurdy** [comment]
The sidebar is defined in [_includes/sidebar.html](https://github.com/poole/hyde/blob/master/_includes/sidebar.html). If you want to removed the "Download" and "Github project" links, you can delete the following code from that file:

```html
<a class="sidebar-nav-item" href="{{ site.github.repo }}/archive/v{{ site.version }}.zip">Download</a>
<a class="sidebar-nav-item" href="{{ site.github.repo }}">GitHub project</a>
```

**Comment by mdo** [comment]
Closing since it's a ghost user now.
