### ISSUE TITLE
Liquid Exception: Couldn't find file 'style.css' in _includes/head.html, included in _layouts/default.html

### ISSUE THREAD

**Issue by jvnvr** [poole/poole#77]
I get this every time on build:
Liquid Exception: Couldn't find file 'style.css' in _includes/head.html, included in _layouts/default.html
jekyll 2.5.3 | Error:  Couldn't find file 'style.css'

I run yo poole, jekyll doctor (all ok), then jekyll build and I get the error. Shouldn't the main css be built from sass? Thanks

**Comment by mdo** [comment]
The CSS isn't powered by Sass yet, that's coming soon. If you've got some custom URLs—even a GitHub Pages one—you might need to update those. Soon that'll be easier.
