### ISSUE TITLE
Page "jumping" around

### ISSUE THREAD

**Issue by diego898** [poole/poole#79]
@mdo I finally made a gif of what I mean. When clicking around page titles I see this: 

![shifting](https://cloud.githubusercontent.com/assets/742407/6278719/0307045a-b84e-11e4-9ae3-8925e74eca65.gif)

Note that the first three links are ok, but for some reason the last two cause a slight right shift. When I click on the first three again, I shift back to the left. 

This happens to me in both chrome 40 and IE 11. Should I make a separate issue for just this jumping around? 

Note: this was also posted on a closed issue but I wasnt sure if it was seen

**Comment by diego898** [comment]
bump

**Comment by lokenx** [comment]
Just tried it out on my machine and I'm not getting the "jumping around" that you're seeing. Tried in Chrome 41 and Safari 8 on OS X 10.10.2. Tried clearing your cache maybe?

**Comment by lokenx** [comment]
Funny enough, on Windows 7 with Chrome 41 and Firefox 35 I'm seeing exactly what you are, so maybe it's a Windows specific issue.

**Comment by nicolasmccurdy** [comment]
If devtools changes its behavior, it could be related to caching or race conditions.

**Comment by diego898** [comment]
@nicolasmccurdy When I have devtools open, the jumping around does indeed stop on windows. Im not exactly clear what is meant by caching or race conditions. Would this be a poole problem or browser problem? Thanks!

**Comment by nicolasmccurdy** [comment]
Sometimes devtools will make changes to how JavaScript/CSS/caching/etc. works when it is open, to help with debugging or prevent cache issues from getting in the way of testing your code. It isn't necessarily a browser problem, but it could be the browser doing something different which causes a bug  in Poole.

**Comment by octref** [comment]
No. I guess the jump is because:
- No scrollbar for pages less than 1 viewport
- Scrollbar for pages more than 1 viewport

The scrollbar takes width and repositions your centered item,

**Comment by lokenx** [comment]
@octref seems to be correct, shorten your viewport (window) so the other two pages run over and the issue goes away.

**Comment by lokenx** [comment]
Could solve by forcing the scroll-bar to always shown?

    html {
        overflow-y: scroll;
    }

**Comment by mdo** [comment]
Yeah, this does seem to be a problem of scrollbars. I've not intention of providing scrollbars are every page though. If you'd like to see that behavior added, please add it as an override on your sites as needed.
