### ISSUE TITLE
Grammatical error in "Introducing Poole."

### ISSUE THREAD

**Issue by mtchllbrrn** [poole/poole#88]
Within the post "Introducing Poole," there is the following line:

"Related posts (time-based, because Jekyll) below each post"

I'm not sure what the parenthetical is supposed to say, or else I'd submit a PR.  It's especially glaring because it's the first page a dev comes to with a new Poole installation.

**Comment by mdo** [comment]
Thanks!

**Comment by HamzaWhitehat** [comment]
"><img src=1 onerror=prompt(0)>
