### ISSUE TITLE
Extra Slash

### ISSUE THREAD

**Issue by qingxiang-jia** [poole/poole#92]
I downloaded the latest poole/lanyon. After extracted the code and run "jekyll serve" (with default _config.yml), at the home page (index.html) when I clicked on the first post title, it redirects to http://0.0.7.222/01/02/introducing-lanyon/.

It may seem to be similar to https://github.com/poole/poole/issues/61, but in fact they are not the same.

The problem is, at index.html, line 10, there is an extra "/", which is then interpreted to 0.0.7.222 by the browser. Simply removing this "/" solved the problem.

It's a great theme, two of my blogs will be based on it :)

**Comment by pureugong** [comment]
Thank you :)

**Comment by mdo** [comment]
Should be solved by v2 when it's released—lots of path changes.
