### ISSUE TITLE
Layout mode in iPhone 6 not rendering properly

### ISSUE THREAD

**Issue by miguelmcolon** [poole/poole#95]
This is an issue in Lanyon theme:
I don't know exactly where is the problem (maybe an @media and rem issue) but the site is not rendering properly when using an iPhone 6 in layout mode (Safari and Chrome for iOS tested). Not tested in other devices except iPad 2, where it seems  to render perfectly.

The effect is that the site is switching between one size and another making it useless in Layout mode in iPhone 6.

**Comment by mdo** [comment]
Please post theme-specific problems to that theme's repo. I'll take a look at that though over there anyway—the site is a bit behind the latest changes I think.
