### ISSUE TITLE
404 on baseurl for github project pages

### ISSUE THREAD

**Issue by ronnyb29** [poole/poole#96]
when following these instructions for hosting on github pages:
http://jekyllrb.com/docs/github-pages/
localhost:4000/project-url-name returns a 404
i don't know if this is a poole issue
i'm specifically using the hyde theme if that changes anything

**Comment by mohammadkhatri** [comment]
just make a try using 
`jekyll serve --baseurl '/project-url-name'`

**Comment by ronnyb29** [comment]
unfortunately didn't work
the website works as planned live, there is just no way to test using 

jekyll serve --baseurl '/project-url-name'

or 

jekyll serve --baseurl ''

**Comment by mdo** [comment]
Should be better once I release v2—we had to fix a bunch of URLs.
