### ISSUE TITLE
Compability with Jekyll 3? 

### ISSUE THREAD

**Issue by joacimmelin** [poole/poole#99]
Hi,

Is Poole compatible with Jekyll 3.0?   (https://github.com/poole/lanyon/issues/124)

If not - any idea when this may be done? 

Thanks,

Joacim

**Comment by barryanders** [comment]
For building, it seems to work just fine for me.

**Comment by joacimmelin** [comment]
I tried to build with the Lanyon theme and got this output: 

"Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check http://jekyllrb.com/docs/upgrading/ for more info."

**Comment by miklb** [comment]
remove `relative_permalinks: true` from config.yml

**Comment by joacimmelin** [comment]
I removed that line and the site builds but it takes about one hour every time. There must be a faster way than this?

**Comment by rajavm** [comment]
any updates on this threads?  regarding 
"Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check http://jekyllrb.com/docs/upgrading/ for more info."

**Comment by ItachiSan** [comment]
Doing like this works fine for me:
ItachiSan/itachisan.github.io@0fa0e1f282daadf526065de4a3f89179ed4c901a

**Comment by leocnj** [comment]
@ItachiSan's method works for me. On my mac book pro with osx 10.11, I haven't met the issue as reported by @joacimmelin - "I removed that line and the site builds but it takes about one hour every time".

**Comment by joacimmelin** [comment]
I assume it takes hours because I have 7500+ posts to process.

**Comment by tomasfejfar** [comment]
I got `jekyll 3.0.2 | Error:  undefined method `each' for "jekyll-paginate":String` with settings below (and current master - 2515dd35ec60d2674fae1108090c12687aa853e4):
```
relative_permalinks: false
gems: jekyll-paginate
```

**Comment by gnujoow** [comment]
I got the same issue @tomasfejfar

**Comment by tomasfejfar** [comment]
I seem to have fixed it with:
`gems:  [jekyll-paginate]`

**Comment by merrymenproductions** [comment]
I commented out the following code, as recommended:
relative_permalinks: true

However, none of the posts are showing on the home page. Does anyone have this same issue?
